### ISSUE TITLE
Compilation error in Linux

### ISSUE THREAD

**Issue by alonsoJASL** [drkarim/lassy#2]
Hello, 
I am trying to compile the source in Ubuntu (16.04), I got a couple of errors (and warnings) trying to compile, which I think are related. I'll document here every error I found and what I did. Hopefully the author can help out. 

1. **CMake error:** `./lassy++/include/LaShell.h Can't be found`. When trying to generate the project I would get this error. I noticed the file `./lassy++/include/lashell.h`, so I just changed its name to `LaShell.h` and was able to generate.

2. **So many warnings** when running `make`. Normally, I tend to ignore the warnings, but in this case I think they might be related to my ultimate issue. I kept getting the following warnings: 
> WARNING:  The current project is configured to use a C++ standard version older than the C++ standard used for this build of ITK
> WARNING:  The current project is configured to use a C++ standard version older than the C++ standard used for this build of VXL

For completeness, my configurations are: 

| CMake         | gcc     | ITK          | VTK     | Qt          |
| :------: | :------: | :------: | :------: | :------: |
| v3.14 | v5.4.0 | v4.13 | v.8.1 | v5.12.2 |

3. **Compilation error** when running make, every step of the compilation shows me one of the previous warnings, ultimately coming to the following error: 

> /path/to/lassy-source/lassy++/src/LaShellPointsCSV.cxx: In member function ‘void LaShellPointsCSV::VisualisePoints()’:
/home/jsl19/installs/lassy-source/lassy++/src/LaShellPointsCSV.cxx:253:28: error: ‘class vtkVertexGlyphFilter’ has no member named ‘AddInput’
         vertexGlyphFilter->AddInput(polydata);
                            ^
lassy++/src/CMakeFiles/lassy++.dir/build.make:361: recipe for target 'lassy++/src/CMakeFiles/lassy++.dir/LaShellPointsCSV.cxx.o' failed
make[2]: *** [lassy++/src/CMakeFiles/lassy++.dir/LaShellPointsCSV.cxx.o] Error 1
CMakeFiles/Makefile2:1126: recipe for target 'lassy++/src/CMakeFiles/lassy++.dir/all' failed
make[1]: *** [lassy++/src/CMakeFiles/lassy++.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

I think the issue could be the versions of the software I am using. I will try it on my personal computer, which is a mac. Hopefully then I can build the project. 

Thanks a lot for the help!

José Alonso

**Comment by alonsoJASL** [comment]
Hi again! I found the problem, in file `./lassy++/src/LaShellPointsCSV.cxx`, the following appears around line `250`: 
```c++
    #if VTK_MAJOR_VERSION <= 5
        vertexGlyphFilter->AddInput(polydata);
    #else
        vertexGlyphFilter->AddInputData(polydata);
    #endif
        vertexGlyphFilter->Update();
```
For some reason, the linux compiler is not understanding this and thus is throwing the error. For now, I have removed the condition as I am using VTK v8.1. The following is what shows instead:
```c++
vertexGlyphFilter->AddInputData(polydata);
vertexGlyphFilter->Update();
```

**Comment by drkarim** [comment]
That's interesting. Thanks for noting what has worked on your Linux distro. The VTK version check can go away soon as very few will be running VTK version 5 or below.

**Comment by alonsoJASL** [comment]
Sounds good! There's only the small issue at the [beginning](https://github.com/drkarim/lassy/issues/2#issue-433209328) that file `./lassy++/include/LaShell.h`had a different name `./lassy++/include/lashell.h`. I don't know if that was by design or just a minor error. Either way, I feel this is pretty much closed.
